apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-streaming
  strategy: {}
  template:
    metadata:
      labels:
        app: video-streaming
    spec:
      imagePullSecrets:
      - name: ocir-registry-secret
      containers:
      - image: ap-seoul-1.ocir.io/cnqphqevfxnp/video-streaming:16
        name: video-streaming
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "80"
        - name: RABBIT
          value: amqp://test:test@rabbit:5672
---
apiVersion: v1
kind: Service
metadata:
  name: video-streaming
spec:
  selector:
    app: video-streaming
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80